spring.application.name=financeiro

spring.datasource.url=jdbc:postgresql://localhost:5432/financeiro_ecoa
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jackson.time-zone=America/Sao_Paulo

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0